from .classifier_mnist import MnistClassifier, load_pretrained_mnist,load_pretrained_fashion
from .classifier_SVHN import SVHNClassifier, load_pretrained_svhn
from .classifier_empty_full import CirclesClassifier
# from .CelebA_classifier import Resnet_classifier_celeba