wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: cond_samples_0x0\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.height
      5: 1
      6:
      - 1
    - 1: generate_joint._type
      5: 1
      6:
      - 1
    - 1: generate_joint.sha256
      5: 1
      6:
      - 1
    - 1: generate_joint.size
      5: 1
      6:
      - 1
    - 1: generate_joint.path
      5: 1
      6:
      - 1
    - 1: generate_joint.format
      5: 1
      6:
      - 1
    - 1: generate_joint.width
      5: 1
      6:
      - 1
    - 1: generate_joint.height
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    python_version: 3.8.13
    start_time: 1666606269.974182
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 256
beta_kl:
  desc: null
  value: 1
beta_prior:
  desc: null
  value: 1
data_path:
  desc: null
  value: ../data/
dcca:
  desc: null
  value: false
decoder dist:
  desc: null
  value: torch.distributions.laplace.Laplace
decoder_dist:
  desc: null
  value: laplace
decrease_beta_kl:
  desc: null
  value: 1
device:
  desc: null
  value: cuda
dist:
  desc: null
  value: laplace
epochs:
  desc: null
  value: 100
experiment:
  desc: null
  value: mmvae/mnist_svhn
fix_decoders:
  desc: null
  value: true
fix_jencoder:
  desc: null
  value: true
freq_analytics:
  desc: null
  value: 5
latent_dim:
  desc: null
  value: 20
learn_prior:
  desc: null
  value: false
llik_scaling:
  desc: null
  value: 0.0
logp:
  desc: null
  value: false
looser:
  desc: null
  value: true
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: mnist_svhn
no_analytics:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
no_nf:
  desc: null
  value: true
no_recon:
  desc: null
  value: false
num_hidden_layers:
  desc: null
  value: 1
obj:
  desc: null
  value: dreg
print_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
skip_warmup:
  desc: null
  value: false
use_pretrain:
  desc: null
  value: ''
use_softmax:
  desc: null
  value: true
wandb_experiment:
  desc: null
  value: mnist_svhn
warmup:
  desc: null
  value: 0
